name: "Terraform Cloud CI"
on:
  push:
    branches:
      - new-feature
  pull_request:
    branches:
      - new-feature

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
      AWS_DEFAULT_REGION: "eu-west-3"
      TF_CLI_CONFIG_FILE: ${{ github.workspace }}/.terraformrc
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.4
      - name: Configure Terraform Cloud Credentials
        run: |
          echo "credentials \"app.terraform.io\" {" > .terraformrc
          echo "  token = \"${TF_CLOUD_TOKEN}\"" >> .terraformrc
          echo "}" >> .terraformrc

      - name: "Terraform Init"
        id: init
        run: |
          cd code/network
          terraform init

      - name: "Terraform Plan"
        id: plan
        run: |
          cd code/network
          terraform plan
