name: AWS Infra Creation Using in TF Cloud
on:
  workflow_call:
    secrets:
      TF_API_TOKEN:
        required: true
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        type: string
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  tfcode_path: code/network

jobs:
  aws_tfc_job:
    name: Create AWS Infra Using TFC

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tf code in runner environment
        uses: actions/checkout@v3.5.2

      # Configure Terraform cloud API token
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

      # Add the AWS Creds as ENV variable in TF Cloud workspace

      - name: Terraform init and validate
        run: |
          echo `pwd`
          echo "** Running Terraform Init**"
          terraform init

          echo "** Running Terraform Validate**"
          terraform validate
        working-directory: ${{ env.tfcode_path }}

      - name: Terraform plan
        run: |
          echo `pwd`
          echo "** Running Terraform Plan**"
          terraform plan
        working-directory: ${{ env.tfcode_path }}
